
spring:
  application:
    name: zuul-service

server:
  port: 8090

eureka:
  instance:
    instance-id: ${spring.application.name}:${random.value}
    status-page-url-path: /swagger-ui.html
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

zuul:
  routes:
    u-student-service:
      service-id: u-student-service
      path: /api/students/**

